{% set version = "2.1.1" %}
{% set name = "jupyterlab-fonts" %}
{% set ns = "@deathbeds" %}
{% set extensions = [
  "jupyterlab-fonts",
  "jupyterlab-font-anonymous-pro",
  "jupyterlab-font-dejavu-sans-mono",
  "jupyterlab-font-fira-code",
] %}

package:
  name: jupyterlab-fonts
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab-fonts/jupyterlab-fonts-{{ version }}.tar.gz
  sha256: 755feaa0fe7a42b25d160df621236d68f05f93f0e1765ce8f09c4348f79c1f7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jupyterlab 3.*
    - python >=3.7

test:
  requires:
    - pip
    - m2-git  # [win]
  imports:
    - jupyterlab_fonts
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    {% for ext in extensions %}
    - grep -iE "{{ ns }}/{{ ext }} v{{ version.replace('.', '\\.') }}.*OK.*\(python, {{ name }}\)" labextensions
    {% endfor %}

about:
  home: https://github.com/deathbeds/jupyterlab-fonts
  summary: Interactive Typography and Style for JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    {% for ext in extensions %}
    - src/jupyterlab_fonts/labextensions/{{ ns }}/{{ ext }}/static/third-party-licenses.json
    {% endfor %}

extra:
  recipe-maintainers:
    - bollwyvl
